version: '3'
services:
  app-spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8090"
    environment:
      - REDIS_HOST=redis
      - SERVER_PORT=8090
  redis:
    image: redis
    #command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
